---
title: "R Notebook"
output: html_notebook
---

```{r}
library(shiny)
library(leaflet)
library(readr)
library(htmltools)
library(ggplot2)
library(scales)

```

```{r}
data = read_csv("ResultsFinal.csv")

data_summarized <- data.frame(Team=unique(data$Team), Points=0, Played=0, Seasons=0, Titles=0, Wins=0, Draws=0, Losses=0, GF=0, GA=0, GD=0, Longitude=0, Latitude=0)

for (i in data_summarized$Team){
  data_summarized$Wins[data_summarized$Team == i] <- sum(data$W[data$Team == i])
  data_summarized$Points[data_summarized$Team == i] <- sum(data$Pts[data$Team == i])
  data_summarized$Draws[data_summarized$Team == i] <- sum(data$D[data$Team == i])
  data_summarized$Losses[data_summarized$Team == i] <- sum(data$L[data$Team == i])
  data_summarized$GF[data_summarized$Team == i] <- sum(data$F[data$Team == i])
  data_summarized$GA[data_summarized$Team == i] <- sum(data$A[data$Team == i])
  data_summarized$GD[data_summarized$Team == i] <- sum(data$GD[data$Team == i])
  data_summarized$Played[data_summarized$Team == i] <- sum(data$P[data$Team == i])
  data_summarized$Seasons[data_summarized$Team == i] <- data_summarized$Played[data_summarized$Team == i]/38
  data_summarized$Titles[data_summarized$Team == i] <- sum(data$Pos[data$Team == i] == 1)
  data_summarized$Longitude[data_summarized$Team == i] <- unique(data$Longitude[data$Team == i])
  data_summarized$Latitude[data_summarized$Team == i] <- unique(data$Latitude[data$Team == i])
}

#summary(data_summarized)
```

```{r}
r_colors <- rgb(t(col2rgb(colors()) / 255))
names(r_colors) <- colors()

ui <- shinyUI(
  fluidPage(
  hr(),
  wellPanel(
  titlePanel("Liga Angielska XXI wiek")
  ),
  hr(),
  wellPanel(
  fluidRow(leafletOutput("mymap", width = "100%", height = 600))),
  hr(),
  wellPanel(
  fluidRow(selectInput("wykres", label = "Wykres", choices = c("Zdobyte punkty", "Strzelone Bramki", "Pozycja w tabeli"), selected = "Zdobyte punkty"),
    plotOutput("grafica"))),
  hr(),
  wellPanel(
  fluidRow(tableOutput("results"))
  ))
)

server <- function(input, output, session) {
  
  # Obserwowanie klikania
  data_of_click <- reactiveValues(clickedMarker=NULL)
  observeEvent(input$mymap_marker_click, {
    data_of_click$clickedMarker <- input$mymap_marker_click
  })
  output$mymap <- renderLeaflet({
      leaflet(data_summarized) %>%
      addTiles() %>%
      addMarkers(~Longitude, ~Latitude) #, popup = ~htmlEscape(Team))
  })
  
  # Do wprowadzania tekstu do popupów
  observe({
        click <- input$mymap_marker_click
       
        if (is.null(click))
            return()
        team <- data_summarized[data_summarized$Longitude == click$lng,]
        
        text <-
            paste(sep = "<br/>", "<b><a>", 
                  team$Team, "</a></b>",
                  "<b>Liczba zdobytych mistrzostw: </b>",
                        team$Titles,  
                        "<b>Liczba sezonów w najwyższej klasie rozgrywkowej: </b>",
                        team$Seasons,
                       "<b>Liczba zdobytych punktów: </b>",
                        team$Points)

        leafletProxy(mapId = "mymap") %>%
            clearPopups() %>%
            addPopups(dat = click, lat = ~lat, lng = ~lng, popup = text)

    })
  
  # Tabela z wynikami
  output$results <- renderTable(
    
    data_summarized[(data_summarized$Longitude == data_of_click$clickedMarker$lng),!(names(data_summarized) %in% c("Longitude", "Latitude"))] #longtitiude jest unikalne dla każdego klubu
    # (data$Latitude == data_of_click$clickedMarker$lat) && 
  )
  
  # Wykresy ze zwyciestwami oraz zdobywanymi punktami
  output$grafica <- renderPlot({
    if (is.null(data_of_click$clickedMarker)){
            return()
    }
    if (input$wykres == "Zdobyte punkty"){
    
     ggplot(data = data[data$Longitude == data_of_click$clickedMarker$lng,], aes(x = year, y = Pts)) + geom_bar(stat="identity", colour = "blue") + xlab("Sezon") + ylab("Suma punktów") + theme(axis.text.x = element_text(angle = 90)) + ggtitle("Punkty zdobyte w XXI wieku") + theme(axis.title = element_text(size = 14)) + theme(axis.text = element_text(size = 12)) + theme(plot.title = element_text(size = 20)) + theme(plot.title = element_text(hjust = 0.5)) 
    }
    else if (input$wykres == "Strzelone Bramki"){
       ggplot(data = data[data$Longitude == data_of_click$clickedMarker$lng,], aes(x = year, y = F)) + geom_bar(stat="identity", colour = "blue") + xlab("Sezon") + ylab("Suma punktów") + theme(axis.text.x = element_text(angle = 90)) + ggtitle("Strzelone bramki w XXI wieku") + theme(axis.title = element_text(size = 14)) + theme(axis.text = element_text(size = 12)) + theme(plot.title = element_text(size = 20)) + theme(plot.title = element_text(hjust = 0.5))
    }
    else if (input$wykres == "Pozycja w tabeli"){
       ggplot(data = data[data$Longitude == data_of_click$clickedMarker$lng,], aes(x = year, y = Pos)) + geom_point(colour = "blue") + xlab("Sezon") + ylab("Suma punktów") + theme(axis.text.x = element_text(angle = 90)) + ggtitle("Pozycja w tableli w XXI wieku") + theme(axis.title = element_text(size = 14)) + theme(axis.text = element_text(size = 12)) + theme(plot.title = element_text(size = 20)) + theme(plot.title = element_text(hjust = 0.5))
    }
  
  })
}

shinyApp(ui, server)
```
